variables:
  #RETROSPEC_TEMPLATES_DIR: /root/.retrospec/repos/retrospec-puppet-templates
before_script:
  - gem install bundler
  - bundle install --without development build
  - bundle exec ruby lib/retrospec/plugins/v1/plugin/templates/clone-hook

image: ruby:2.5

ruby2.3:
  stage: test
  tags:
    - ruby
  script:
    - "bundle exec rake spec"
  image: ruby:2.3

ruby2.4:
  stage: test
  tags:
    - ruby
  script:
    - "bundle exec rake spec"
  image: ruby:2.4

ruby2.5:
  stage: test
  tags:
    - ruby
  script:
    - "bundle exec rake spec"
  image: ruby:2.5

stages:
  - validate
  - test
  - release
  - deploy

rubocop_ruby:
  stage: validate
  allow_failure: true
  only:
    - branches
  tags:
    - ruby
  script:
    - bundle install
    - bundle exec rubocop -D

bump_and_tag:
  type: release
  when: manual
  tags:
    - ruby
  only:
    - master@nwops/puppet-retrospec
  script:
    - gem install release_me
    - bump_and_tag

production:
  tags:
    - ruby
  before_script:
    - gem install dpl
  type: deploy
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tags
